---
title: 'opticut: likelihood based optimal partitioning for indicator species analysis'
author: "Peter Solymos and Ermias T. Azeria"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document:
    keep_tex: no
    toc: true
    toc_depth: 3
    number_sections: false
  word_document:
    toc: true
    toc_depth: 3
documentclass: report
fontsize: 11pt
classoption: letterpaper
---

# Introduction

## Install

## License

## Issues

# Partitioning for single species

## All combinations

* explain all comb, wplot, plot
* explain object structure
* use Gaussian toy data
* fixlevels, summary, plot, beta2i

## User defined combinations

* show user defined strata matrix

## Rank based combinations

* plot, summary

# Partitioning for multiple species

* interface, object structure
* bestpart, bestmodel, summary, print
* wplot, plot, all/rank comb (custom strata)

# Quantifying uncertainty

* anymp/boot/multi
* explain object structure (toy data)
* bestpart, summary
* jackknife, check_strata, heatmap etc.
* custom dist: cannot return bestmodel, use bestpart to refit
* custom dist: can do boot & multi, but not asymp, show how to get I

# Distributions

* dolina data set: use wherever possible
* modification
* offsets

## Gaussian

## Binomial

## Beta

## Poisson and Negative Binomial

## Zero-inflated distributions

## Ordinal data

## Presence-only (use-availability) data

## Mixed-effects models (LMM, GLMM)

## Generalized additive models (GAM)

## N-mixture models

# Package options

## High performance computing

## Global options

## Color themes

## Dynamic documents


```{r}
library(opticut)
ocoptions(try_error=TRUE)
library(optpart)

data(shoshsite)
data(shoshveg)

elev <- cut(shoshsite$elevation, breaks=c(0, 7200, 8000, 9000, 20000))
levels(elev) <- c("low","mid1","mid2", "high")

sveg <- as.matrix(shoshveg)
sveg[sveg > 0] <- 1
o <- opticut(sveg ~ 1, strata=elev, dist="binomial")
plot(o, sort=1)


sveg <- as.matrix(shoshveg)
sveg <- sveg[,colSums(sveg>0) >= 50]
table(sveg)
sveg[sveg==0] <- 0.001
sveg[sveg==0.1] <- 0.01
sveg[sveg==0.5] <- 0.05
sveg[sveg==1] <- 0.15
sveg[sveg==2] <- 0.25
sveg[sveg==3] <- 0.35
sveg[sveg==4] <- 0.45
sveg[sveg==5] <- 0.55
sveg[sveg==6] <- 0.65
sveg[sveg==7] <- 0.75
sveg[sveg==8] <- 0.8
table(sveg)
o2 <- opticut(sveg ~ 1, strata=elev, dist="beta")
plot(o2, sort=1)

sveg2 <- as.matrix(shoshveg)
sveg2[sveg2 > 0] <- 1
sveg2 <- sveg2[,colnames(sveg)]
o3 <- opticut(sveg2 ~ 1, strata=elev, dist="binomial")
plot(o3, sort=1)

sveg2 <- as.matrix(shoshveg)
sveg2[sveg2 > 0] <- 1
sveg2 <- sveg2[,colnames(sveg)]

Y <- shoshveg$ASTMIS
table(Y)
o4 <- opticut(Y ~ 1, strata=elev, dist="ordered")
o4$species

## check for modifier variable
```
